### ISSUE TITLE
line 137 if ret != 0 local variable 'ret' referenced before assignment

### ISSUE THREAD

**Issue by necrolyte2** [VDBWRAIR/pyBWA#2]
line 137 if ret != 0 local variable 'ret' referenced before assignment

Not exactly sure how to duplicate this, but it is there

**Comment by necrolyte2** [comment]
```
Traceback (most recent call last):
  File "/home/AMED/tyghe.vallard/.ngs_mapper/bin/run_bwa_on_samplename.py", line 4, in <module>
    __import__('pkg_resources').run_script('ngs-mapper==1.0.0', 'run_bwa_on_samplename.py')
  File "/home/AMED/tyghe.vallard/.ngs_mapper/lib/python2.7/site-packages/pkg_resources.py", line 517, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/AMED/tyghe.vallard/.ngs_mapper/lib/python2.7/site-packages/pkg_resources.py", line 1423, in run_script
    exec(code, namespace, namespace)
  File "/home/AMED/tyghe.vallard/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.0.0-py2.7.egg/EGG-INFO/scripts/run_bwa_on_samplename.py", line 8, in <module>
    run_bwa.main()
  File "/home/AMED/tyghe.vallard/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.0.0-py2.7.egg/ngs_mapper/run_bwa.py", line 55, in main
    pairedsai = bwa_mem( reads['F'], reads['R'], ref, join(tdir, 'paired.sai'), t=args.threads )
  File "/home/AMED/tyghe.vallard/.ngs_mapper/lib/python2.7/site-packages/ngs_mapper-1.0.0-py2.7.egg/ngs_mapper/run_bwa.py", line 188, in bwa_mem
    if not index_ref(ref):
  File "/home/AMED/tyghe.vallard/.ngs_mapper/lib/python2.7/site-packages/bwa/bwa.py", line 142, in index_ref
    if ret != 0:
UnboundLocalError: local variable 'ret' referenced before assignment
```
